version: "3"
services:
  react-app:
    image: my-react-app
    container_name: react-app
    restart: always
    expose:
      - "3000"
    networks:
      - web

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/yourdomain.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/yourdomain.com/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - react-app
    networks:
      - web

networks:
  web:
    driver: bridge
