version: "3.8"
services:
  react-app:
    build: .
    container_name: react-app
    restart: always
    ports:
      - "8080:80"
    networks:
      - proxy-network
    volumes:
      - /etc/letsencrypt/live:/etc/letsencrypt/live
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive

networks:
  proxy-network:
    external: true
