version: "3"
services:
  react-app:
    build: .
    container_name: react-app
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live:/etc/letsencrypt/live
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive
    networks:
      - app-network

networks:
  app-network:
